[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; ==== CẤU HÌNH BỘ NHỚ ====
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi

; ==== CỜ BIÊN DỊCH BẮT BUỘC ====
build_flags = 
    -D BOARD_HAS_PSRAM
    -D FIXED_POINT=1 
    -D USE_KISS_FFT
    -D VAR_ARRAYS
    -I src

; ==== THƯ VIỆN ====
lib_deps = 
    https://github.com/pschatzmann/arduino-audio-tools.git
    https://github.com/xiph/speex/archive/refs/heads/master.zip
    sandeepmistry/LoRa @ ^0.8.0
    olikraus/U8g2 @ ^2.34.22
    mikalhart/TinyGPSPlus @ ^1.1.0